### ISSUE TITLE
Problem with Serial Comunication

### ISSUE THREAD

**Issue by pep248** [MuSAELab/BLE-Toolkit-LabVIEW#2]
Hello.
These days I've been trying to communicate arduino and labview through Bluetooth low energy.

We wanted to acquire and send data from Bluetooth device.

with a mobile app, we acquired the service name and characteristics:

![whatsapp image 2018-04-23 at 16 27 32](https://user-images.githubusercontent.com/38502977/39133988-d156e5d8-4715-11e8-9dc0-a8754001599c.jpeg)

I modified the program to acquire the name of the device, to instead, acquire the data sent to the device, replacing the example services, and introducing my custom services, seen in the image:

![imatge](https://user-images.githubusercontent.com/38502977/39133965-c47866b6-4715-11e8-9beb-7c23988030f2.png)

(I've tried with 0000ffe0-0000-1000-8000-00805f9b34fb instead of FFE0 but the error is the same)

It was a shame, but trying to get data from a service didn't seem an option so then I tried to acquire data from the serial port:

![dubte](https://user-images.githubusercontent.com/38502977/39132749-e5f81604-4712-11e8-9a45-bc18477a9937.png)

And it worked!

The problem is that no matter how I modify it, i can't send data through the serial port. I can receive, but I can't send.

Could you give me any help?

[main.zip](https://github.com/MuSAELab/BLE-Toolkit-LabVIEW/files/1938764/main.zip)

**Comment by rcassani** [comment]
These are some points that may help you at finding the problem.
1. What does the error say?
2. Are your service (FFE0) and characteristic (FFE1) listed in the Handle Table?
3. If your device is sending the characteristic values, they will detected as **Events**, try to use the  `ble_evt_attclient_attribute_value.vi` in the While loop. This is shown in the example `ble_read_hr_monitor.vi` which is installed in the LabVIEW example folder (mine is `C:\Program Files (x86)\National Instruments\LabVIEW 2013\examples\BLE`)
4. The BLE-Toolkit-LabVIEW is wrapper for serial communication with the BLED112 dongle. By reading and writing directly on the serial port, you need to be aware of the format of the data received [BGAPI protocol](http://www.silabs.com/documents/login/reference-manuals/Bluetooth_Smart_Software-BLE-1.3-API-RM.pdf)

**Comment by pmn1966** [comment]
I link to this issue/question instead of copy it here. :-)


https://forums.ni.com/t5/LabVIEW/LabVIEW-BLE-Bluetooth-Low-Energy-toolkit-and-Inkbird-IBT6X/m-p/4058349?profile.language=en#M1164542

**Comment by rcassani** [comment]
Ping @pep248

**Comment by rcassani** [comment]
Closed because inactivity
