### ISSUE TITLE
iBeacon handling

### ISSUE THREAD

**Issue by Schmubi** [MuSAELab/BLE-Toolkit-LabVIEW#4]
Hi
I want to use BLE-Toolkit-LabVIEW to connect with a BLE device that advertises with iBeacon format. I was not able to see it in the scan output. Is there a chance to do this?
Thanks.

**Comment by wheelsailor** [comment]
Check my post here https://forums.ni.com/t5/Community-Documents/LabVIEW-BLE-Bluetooth-Low-Energy-toolkit/ta-p/3538612 on 08-12-2019. Does that help?
Nick

**Comment by rcassani** [comment]
Ping @Schmubi

**Comment by rcassani** [comment]
Closed because inactivity
