### ISSUE TITLE
BLE and Inkbird IBT6X termometer?

### ISSUE THREAD

**Issue by pmn1966** [MuSAELab/BLE-Toolkit-LabVIEW#5]
I link to this issue/question instead of copy it in here. :-)

https://forums.ni.com/t5/LabVIEW/LabVIEW-BLE-Bluetooth-Low-Energy-toolkit-and-Inkbird-IBT6X/td-p/4058349?profile.language=en

Any idea what i can do?

**Comment by rcassani** [comment]
My guess is that the temperatures are "Notifications", thus it seems that beside the:

**“RealtimeDataEnableMessage”  {0x0B, 0x01, 0x00, 0x00, 0x00, 0x00} to 0xFFF5 on Service 0xFFF0**

You need to enable (send a value of **1**) to “Client Characteristic Configuration Descriptor” of the desired Characteristic. ([Some extra information](https://www.oreilly.com/library/view/getting-started-with/9781491900550/ch04.html)). In the BLE-Toolkit, there is an example that does this:

https://github.com/MuSAELab/BLE-Toolkit-LabVIEW/blob/master/ble_toolkit_source/examples/ble_read_hr_monitor.vi

Just before the while loop, there is the `ble_write_client_characteristic_configuration` VI that enables the (heart rate) characteristic to notify its values.

On last thing, you may need to try in different order:

1) First the "RealtimeDataEnableMessage" and after enable the CCCD
2) or first the CCCD and then the "RealtimeDataEnableMessage"

Let me know if this works.

**Comment by rcassani** [comment]
Ping @pmn1966

**Comment by rcassani** [comment]
Closed by inactivity
