### ISSUE TITLE
BLE Toolkit Friendly name 

### ISSUE THREAD

**Issue by ggasson** [MuSAELab/BLE-Toolkit-LabVIEW#6]
Hi, the friendly name is juberish when using the latest toolkit or is there something I am doing wrong?

**Comment by rcassani** [comment]
Hi @ggasson , that "fiendly name" field is ALL the `response data` provided by the BLE devices when scanning.
[Page 109 in BLE API documentation](https://www.silabs.com/documents/public/reference-manuals/Bluetooth-LE-Software-API%20Reference-Manual-for-BLE-Version-1.10.pdf#page=109)

In many devices, it contains ASCII characters that allow to identify the device. However as you have seen, other devices just provide data that is not human readable. 

To get a the `Device Name`, you'd need to connect to the device with its MAC, and read the Service:Characteristic `0x1800:0x2A00`. This is done in the `ble_scan_devices.vi` in the toolkit
